// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psllpclpweaujhkcsrdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbGxwY2xwd2VhdWpoa2NzcmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMTYyNjEsImV4cCI6MjA1MzY5MjI2MX0.yDi_vnasze76SIP5ifXZ_aDp0cYfyYpxW3p23gAOU-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
